name: EntWatchSharp BUILD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  PROJECT_PATH: "EntWatchSharp.sln"
  PROJECT_NAME: "EntWatchSharp"
  OUTPUT_PATH: "./build"

jobs:
  build:
    permissions: write-all
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Restore
      run: dotnet restore
    - name: Build
      run: dotnet build ${{ env.PROJECT_PATH }} -c Release
  publish:
    if: github.event_name == 'push'
    permissions: write-all
    runs-on: windows-latest
    needs: build
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Restore
      run: dotnet restore
    - name: Build
      run: dotnet build ${{ env.PROJECT_PATH }} -c Release
    - name: Set build version
      run: |
        $VER = Get-Content VERSION
        echo ("BUILD_NUMBER=$VER") >> $env:GITHUB_ENV
    - name: Zip
      run: |
        cd ${{ env.OUTPUT_PATH }}
        Compress-Archive -Path * -Destination "../${{ env.PROJECT_NAME }}-v.${{ env.BUILD_NUMBER }}.zip"
    - name: Publish plugin
      uses: ncipollo/release-action@v1.12.0
      with:
        artifacts: "${{ env.PROJECT_NAME }}-v.${{ env.BUILD_NUMBER }}.zip"
        name: "${{ env.PROJECT_NAME }}-v.${{ env.BUILD_NUMBER }}"
        tag: "${{ env.PROJECT_NAME }}-v.${{ env.BUILD_NUMBER }}"
        generateReleaseNotes: true
        makeLatest: true
        body: |
          [Core]${{ env.PROJECT_NAME }} release ${{ env.BUILD_NUMBER }} for CS#. Notify players about entity interactions.
